### ISSUE TITLE
words with diacritics in rule editor

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool-community-website#24]
Characters with diacritics are not handled properly in the rule editor (both expert and simple mode). I have never found this behavior before.

Put a word like "pàgina" in an example sentence, and it is analyzed as having three tokens: "p" "?" "gina".

**Comment by danielnaber** [comment]
Should be fixed now. `catalina.sh` needs this line, it got lost during a security update:
`JAVA_OPTS="-Xmx1600M -Dfile.encoding=utf-8"`

**Comment by jaumeortola** [comment]
There is now some related problem. If you write some character with diacritics in the expert rule editor, you get  `Message: Invalid byte 2 of 3-byte UTF-8 sequence.`

**Comment by danielnaber** [comment]
Probably some Tomcat issue:

	02/02 11:11:47 ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver  - MalformedByteSequenceException occurred when processing request: [POST] /ruleEditor/checkXml
	Invalid byte 1 of 1-byte UTF-8 sequence.. Stacktrace follows:
	com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
		at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
		at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
		at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
		at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
		at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
		at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
		at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
		at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
		at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
		at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
		at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
		at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
		at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
		at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
		at org.languagetool.rules.patterns.PatternRuleLoader.getRules(PatternRuleLoader.java:73)
		at org.languagetool.RuleEditorController$_closure4.doCall(RuleEditorController.groovy:109)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

**Comment by danielnaber** [comment]
@jaumeortola any idea when this started to appear again?

**Comment by jaumeortola** [comment]
For me, today. I would say that a week ago it worked well.

**Comment by danielnaber** [comment]
Not sure what caused it (probably some security update), but adding `export LANG=de_DE.UTF-8` to `/etc/init.d/tomcat8` seemed to fix this.
